### ISSUE TITLE
Error loading UI

### ISSUE THREAD

**Issue by PatrickDanino** [transmission-web-control/transmission-web-control#41]
- Transmssion version: 3.0.0.3
- Tr Web Control version: 1.6.11
- Browser name & version：Chrome
- Problem description: Install succeeded, but the following errors appear in the console:

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

Uncaught ReferenceError: system is not defined
    at HTMLDivElement.onResize (eval at parseOptions (jquery.easyui.min.js?v=20200914:122:6), <anonymous>:3:57)
    at _212 (jquery.easyui.min.js?v=20200914:2963:15)
    at HTMLDivElement.<anonymous> (jquery.easyui.min.js?v=20200914:3484:1)
    at Function.each (jquery-1.12.4.min.js:2:2881)
    at n.fn.init.each (jquery-1.12.4.min.js:2:846)
    at Object.resize (jquery.easyui.min.js?v=20200914:3483:11)
    at $.fn.panel (jquery.easyui.min.js?v=20200914:3412:32)
    at _3ba (jquery.easyui.min.js?v=20200914:5231:13)
    at HTMLDivElement.<anonymous> (jquery.easyui.min.js?v=20200914:5647:1)
    at Function.each (jquery-1.12.4.min.js:2:2881)
```

**Comment by PatrickDanino** [comment]
Additional info:

v1.6.7 works
v1.6.8 fails to install
v1.6.9 does not work

**Comment by trim21** [comment]
v1.6.8 is not released

I'll take a look later this day

**Comment by trim21** [comment]
Can you provide a screenshot?

**Comment by PatrickDanino** [comment]
It seems v1.6.5 and later have a different issue (transmission object cannot be found). v1.6.4 appears to be working properly.

<img width="882" alt="Screenshot 2023-04-23 at 8 57 02 PM" src="https://user-images.githubusercontent.com/2147349/233896892-1cb4c9bf-a7be-437d-94a1-485bf5a550fa.png">
<img width="543" alt="Screenshot 2023-04-23 at 8 56 09 PM" src="https://user-images.githubusercontent.com/2147349/233896894-9adfdd4c-891c-4548-bceb-befbef45cf1c.png">

**Comment by trim21** [comment]
please try v1.6.12

**Comment by PatrickDanino** [comment]
v1.6.12 seems to be working.
